server:
#  port: 9000
  servlet:
    context-path: /api
  address: https://smart-campus-api.onrender.com

#Service Discovery
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:password@localhost:8088/eureka

#Database
spring:
  datasource:
    url: jdbc:mysql://u8cbtbgvdiqpfsz5:V5uwAIEbrYdAfzQ6mzbr@bcvqfixonw1vjbg8hkrn-mysql.services.clever-cloud.com:3306/bcvqfixonw1vjbg8hkrn
    username: u8cbtbgvdiqpfsz5
    password: V5uwAIEbrYdAfzQ6mzbr
  jpa:
    hibernate:
      ddl-auto: update
  application:
    name: smart-campus

app:
  otp:
    attempt: 8

security:
  jwt:
    authUrl: /**/auth/**/
    header: Authorization
    prefix: Bearer
    secret: 2tIenCNhOwiZosM5
    expiration: 3600
