server:
#  port: 9000
  servlet:
    context-path: /api

#Service Discovery
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:password@localhost:8088/eureka

#Database
spring:
  datasource:
    url: jdbc:mysql://mysqldb:3307/smart_campus
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  application:
    name: smart-campus

app:
  otp:
    attempt: 8

security:
  jwt:
    authUrl: /**/auth/**/
    header: Authorization
    prefix: Bearer
    secret: 2tIenCNhOwiZosM5
    expiration: 3600
