server:
  port: 9001
  servlet:
    context-path: /api

#Service Discovery
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://eureka:password@localhost:8089/eureka

#Database
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/smart_campus
    username: root
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
  application:
    name: student-service

app:
  otp:
    attempt: 8

security:
  jwt:
    authUrl: /**/auth/**/
    header: Authorization
    prefix: Bearer
    secret: 2tIenCNhOwiZosM5
    expiration: 3600

auth:
  service:
    url:
      base: http://localhost:9000/api/v1/auth
      validate-token: ${auth.service.url.base}/validate-token