server:
  port: 8089
#  servlet:
#    context-path: /api

#Service Discovery
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:password@localhost:8088/eureka

management:
  endpoint.gateway.enabled: true
  endpoints.web.exposure.include: gateway

#Logging
logging:
  level:
    root: INFO
    org:
      springframework:
        cloud:
          gateway: TRACE
          route:
            RouteDefinitionLocator: INFO

#Database
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/smart_campus
    username: root
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: discovery-service
          uri: lb://discovery-service
          predicates: Path=/eureka/web
          filters: SetPath=/

        - id: auth-service
          uri: lb://auth-service
          predicates: Path=/api/**
          filters: AuthenticationFilter

        - id: student-service
          uri: lb://student-service
          predicates: Path=/api/**
          filters: AuthenticationFilter

        - id: discovery-server-static-resource
          uri: http://localhost:8088
          predicates: Path=/eureka/**

app:
  otp:

auth:
  service:
    url:
      validate:
        token: http://auth-service/api/v1/auth/validate-token?

security:
  jwt:
    authUrl: /**/auth/**/
    header: Authorization
    prefix: Bearer
    secret: 2tIenCNhOwiZosM5
    expiration: 3600
