server:
  port: 9000
  servlet:
    context-path: /api

#Database
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/smart_campus
    username: root
    password: admin
  jpa:
    hibernate:
      ddl-auto: update

app:
  otp:
    attempt: 8

security:
  jwt:
    authUrl: /**/auth/**/
    header: Authorization
    prefix: Bearer
    secret: 2tIenCNhOwiZosM5
    expiration: 3600
